import React, { useMemo, useState } from "react";
import style from "../styles/gridGallery.module.css";
import { projects } from "../data/projects_data";
import Image from "next/image";
import Modal from "./Modal";
import { motion } from "framer-motion";
import { SyncLoader } from "react-spinners";
import { useEffect } from "react";
//import framer animation object
import { animateSlideDown } from "../data/framer-motion config";

function GridGallery() {
  const [modalIndex, setModalIndex] = useState(0);
  const [state, setState] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  // class name is generated by next.js. So i had to copy from the inspector
  // and paste the real or generated class name into the code directly.
  function toggleModal(e) {
    e.preventDefault();
    setModalIndex(e.currentTarget.id);
    setState((prevToggle) => !prevToggle);
  }

  return (
    <>
      <div className={style.galleryGrid}>
        {projects.map((project, index) => (
          <motion.div
            className={style.front}
            style={{ position: "relative" }}
            key={index}
          >
            <motion.div
              className={isLoading ? style.loadingContainer : ""}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1, background: "#ECB365", zIndex: 100 }}
              exit={{ opacity: 0, backgroundColor: "transparent" }}
              transition={2}
            >
              <SyncLoader
                color="#064663"
                style={isLoading ? { display: "block" } : { display: "none" }}
              />
            </motion.div>
            <motion.div
              id={`image-${index}`}
              variants={animateSlideDown}
              initial={animateSlideDown.initial}
              viewport={{
                once: true,
              }}
              whileInView={animateSlideDown.animate}
              transition={{
                ...animateSlideDown.transition,
                delay: 0.2 * index,
              }}
              onClick={(e) => {
                toggleModal(e);
              }}
              className={style.gridItem}
            >
              <Image
                loading="lazy"
                className={style.galleryImg}
                src={project.src}
                onLoad={() => {
                  setIsLoading((prevLoading) => (prevLoading = false));
                }}
                alt={project.alt}
              />

              <div className={style.overlay}>
                <div id={index} className={style.overlayContainer}>
                  <p className={style.overlayText}>{project.Header}</p>
                </div>
              </div>
            </motion.div>
          </motion.div>
        ))}
      </div>
      <div
        onClick={(e) => {
          toggleModal(e);
        }}
      >
        {state && <Modal id={modalIndex} />}
      </div>
    </>
  );
}

export default GridGallery;
