import React, { useMemo, useState } from "react";
import styles from "../styles/gridGallery.module.css";
import { projects } from "../data/projects_data";
import Image from "next/image";
import Modal from "./Modal";
import { motion, AnimatePresence } from "framer-motion";

function GridGallery() {
  const [modalIndex, setModalIndex] = useState(0);
  const [state, setState] = useState(false);

  //classname is generated by next.js. So i had to copy from the inspector
  // and paste the real or generated classname into the code directly.
  console.log(state);
  function toggleModal(e) {
    e.preventDefault();
    setModalIndex(e.currentTarget.id);
    //console.log(e.currentTarget.className);
    if (!state) {
      setState((prevToggle) => (prevToggle = true));
      return;
    }
    console.log(e.target.className);
    setState((prevToggle) => (prevToggle = false));
  }

  const slides = useMemo(() => {
    const slide = projects.map((project, index) => (
      <motion.div
        initial={{ opacity: 0, y: 50 }}
        viewport={{
          once: true,
        }}
        whileInView={{
          opacity: 1,
          y: 0,
          transition: { duration: 1, delay: 0.09 * index },
        }}
        onClick={(e) => {
          toggleModal(e);
        }}
        id={index}
        key={index}
        className={styles["gridItem"]}
      >
        <div className={styles.front}>
          <Image src={project.src} loading="eager" objectPosition={"initial"} />
          <div className={styles.overlay}>
            <div id={index} className={styles.overlayContainer}>
              <p className={styles.overlayText}>{project.Header}</p>
            </div>
          </div>
        </div>
      </motion.div>
    ));
    return slide;
  }, []);

  return (
    <AnimatePresence initial={false} onExitComplete={true}>
      <main>
        <div className={styles.galleryGrid}>{slides}</div>
        <div
          on
          onClick={(e) => {
            toggleModal(e);
          }}
        >
          {state && <Modal id={modalIndex} />}
        </div>
      </main>
    </AnimatePresence>
  );
}

export default GridGallery;
