import React from "react";
import Image from "next/image";
import styles from "../styles/Modal.module.css";
import { projects } from "../data/projects_data";
import { domAnimation, motion, AnimatePresence } from "framer-motion";
import { modal } from "../data/framer-motion config";

function Modal({ id, state, setToggleModal }) {
  //classname is generated by next.js. So i had to copy from the inspector
  // and paste the real or generated classname into the code directly.
  console.log(state);
  function modalClose(e) {
    e.preventDefault();
    if (state && e.target.className === "Modal_modalImage__eaytF") {
      setToggleModal((prevToggle) => (prevToggle = true));
      return;
    }
    setToggleModal((prevToggle) => (prevToggle = false));
  }
  return (
    <AnimatePresence initial={true} exitBeforeEnter={true}>
      {/* 
      if state variable is true then display modal else 
      display empty div.
    */}

      <motion.div
        features={domAnimation}
        variants={modal}
        initial={modal.initial}
        animate={modal.animate}
        exit={modal.exit}
        onClick={(e) => {
          modalClose(e);
        }}
        className={styles.modalContainerOpen}
      >
        <motion.div
          className={styles.modalInnerContainer}
          variants={modal}
          initial={modal.initial}
          animate={modal.animate}
          exit={modal.exit}
        >
          <Image
            layout="fill"
            src={projects[id] ? projects[id].src : alert("error id = null")}
            className={styles.modalImage}
          />
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

export default Modal;
