import React, { useEffect } from "react";
import Image from "next/image";
import styles from "../styles/Modal.module.css";
import { projects } from "../data/projects_data";

function Modal({ id, state, setToggleModal }) {
  //classname is generated by next.js. So i had to copy from the inspector
  // and paste the real or generated classname into the code directly.
  function modal(e) {
    if (e.target.className == "Modal_modalImage__eaytF") {
      //console.log("do not close");
      setToggleModal((prev) => (prev = true));
      return;
    }
    setToggleModal((prev) => (prev = false));
    //console.log("close the modal");
  }

  //console.log("state: " + state);
  return (
    <>
      {/* 
      if state variable is true then display modal else 
      display empty div.
    */}
      {state ? (
        <div onClick={(e) => modal(e)} className={styles.modalContainer}>
          <div className={styles.modalInnerContainer}>
            <Image
              layout="fill"
              src={projects[id] ? projects[id].src : alert("error id = null")}
              className={styles.modalImage}
            />
          </div>
        </div>
      ) : (
        ""
      )}
    </>
  );
}

export default Modal;
