import React from "react";
import Head from "next/head";
import { projects } from "../data/projects_data";
import styles from "../styles/Projects.module.css";
import GridGallery from "../Components/GridGallery";

function Projects() {
  return (
    <>
      <Head>
        <title>Nick - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/DominicGaonaTabLogo.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <GridGallery />
      </main>
    </>
  );
}

export default Projects;
