import React from "react";
import Head from "next/head";
import Skillstyle from "../styles/Skills.module.css";
import Image from "next/image";
import { m, LazyMotion, domAnimation } from "framer-motion";

function Skills() {
  return (
    <main className={Skillstyle.skills_container}>
      <Head>
        <title>Nick - Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/DominicGaonaTabLogo.ico" />
      </Head>
      <LazyMotion features={domAnimation}>
        <div className={Skillstyle.skills_container_inner}>
          <div className={Skillstyle.left}>
            <h2>My Skills</h2>
            <p className={Skillstyle.paragraph}>
              As a versatile developer proficient in front-end and back-end
              technologies, I bring a comprehensive skill set to the table. With
              expertise in Vue.js, React.js, Node.js, Express.js, JavaScript,
              HTML, CSS, and APIs, I can develop a wide range of applications.
              On the front-end, I leverage Vue.js and React.js to create
              intuitive user interfaces and interactive components, ensuring
              pixel-perfect designs and responsive layouts using HTML and CSS.
              JavaScript adds dynamic functionalities and enhances user
              experiences.
            </p>
            <br />
            <p className={Skillstyle.paragraph}>
              When it comes to the back-end, I excel in building robust
              server-side applications using Node.js and Express.js. Whether
              it's developing a store-front or an e-commerce solution,
              integrating payment gateways, or managing product catalogs, I have
              the skills to deliver scalable solutions. I also have experience
              in working with relational and non-relational databases, such as
              Oracle Database and MongoDB, respectively. I can design schemas,
              write SQL queries, and optimize performance in relational
              databases, while also leveraging the flexibility and scalability
              of non-relational databases for handling unstructured or
              semi-structured data.
            </p>
            <br />
            <p className={Skillstyle.paragraph}>
              Additionally, I have a knack for developing visually appealing and
              functional portfolio websites, showcasing your skills and
              projects. By blending my front-end expertise with back-end
              functionalities, I ensure a seamless user experience. Furthermore,
              I can integrate APIs, enabling features like social media
              authentication, data retrieval, and third-party integrations.
            </p>
            <br />
            <p className={Skillstyle.paragraph}>
              With my comprehensive knowledge and experience across these
              technologies, I am well-equipped to deliver high-quality,
              scalable, and customized solutions for your specific needs.
            </p>
          </div>
          <div className={Skillstyle.right}>
            <div className={Skillstyle.imageContainer}>
              <Image
                className={Skillstyle.gears}
                layout="intrinsic"
                src={require("../public/img/skills/Layer 1 copy.png")}
              />
              <Image
                src={require("../public/img/skills/Layer 1.png")}
                loading="lazy"
                className={Skillstyle.image}
                alt="skill image "
              />
            </div>
          </div>
        </div>
      </LazyMotion>
    </main>
  );
}

export default Skills;
